//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadenaUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PadenaUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: Padena Utility v2.0 
        ///Copyright (c) Microsoft 2010, 2011
        ///
        ///Usage:	 PadenaUtil.exe assemble [options] &lt;Read File&gt; 		
        ///	 Assemble reads into contigs (No matepair information required.) 
        ///
        ///Optional Parameters:
        ///-k:&lt;int&gt;           Length of k-mer.
        ///
        ///-d:&lt;int&gt;           Threshold for removing 
        ///                   dangling ends in graph.
        ///
        ///-r:&lt;int&gt;    	   Length Threshold for 
        ///                   removing redundant paths in graph.
        ///-e:&lt;int&gt;           Threshold for eroding low coverage ends.
        ///
        ///-i      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssembleHelp {
            get {
                return ResourceManager.GetString("AssembleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: PaDeNA Utility v2.0 
        ///Copyright (c) Microsoft 2010, 2011
        ///
        ///Usage:	 PadenaUtil.exe assemblewithscaffold [options] &lt;Read File&gt; 		
        ///	 Assemblewithscaffolds merges reads into scaffolds using matepair information.
        ///
        ///Optional Parameters:
        ///
        ///-n:&lt;string&gt;    Clone Library Name.
        ///
        ///-m:&lt;double&gt;    Mean Length of clone library. 
        ///
        ///-s:&lt;double&gt;    Standard Deviation of Clone Library.
        ///
        ///-b:&lt;int&gt;       Number of paired read required to 
        ///	       connect two contigs.
        ///
        ///-f:&lt;int&gt;       Depth for graph traversal. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssembleWithScaffoldHelp {
            get {
                return ResourceManager.GetString("AssembleWithScaffoldHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: PaDeNA Utility v2.0 
        ///Copyright (c) Microsoft 2010, 2011
        ///
        ///Usage:	   PadenaUtil.exe command [options]
        ///
        ///Command:   
        ///
        ///Assemble:              Assemble reads into contigs 
        ///		       (No matepair information required.) 
        ///
        ///Scaffold:     	       Scaffold uses mate pair information 
        ///		       to merge contigs into scaffolds.
        ///
        ///AssembleWithScaffold:  Assemble reads into scaffolds using 
        ///                       matepair information.
        ///.
        /// </summary>
        internal static string PadenaUtilHelp {
            get {
                return ResourceManager.GetString("PadenaUtilHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference File not in correct format.
        /// </summary>
        internal static string ReferenceFile {
            get {
                return ResourceManager.GetString("ReferenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: PaDeNA Utility v2.0 
        ///Copyright (c) Microsoft 2010, 2011
        ///
        ///Usage:	 PADENAUtil.exe scaffold [options] &lt;Contig file&gt; &lt;Read File&gt; 		
        ///	 Scaffold uses mate pair information to merge contigs into scaffolds.
        ///
        ///Required Parameters:
        ///
        ///-k:&lt;int&gt;           Length of k-mer.
        ///
        ///Optional Parameters:
        ///
        ///-h                 Help.
        ///
        ///-o:&lt;Filename&gt;      Output file.
        ///
        ///-n:&lt;string&gt;        Clone Library Name.
        ///
        ///-m:&lt;double&gt;        Mean Length of clone library.
        ///
        ///-s:&lt;double&gt;  	   Standard Deviation of Clone Library. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScaffoldHelp {
            get {
                return ResourceManager.GetString("ScaffoldHelp", resourceCulture);
            }
        }
    }
}
