//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSLocalBuildAgentLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFSLocalBuildAgentLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation Run completed at: .
        /// </summary>
        internal static string AutomationFinishTime {
            get {
                return ResourceManager.GetString("AutomationFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation Run started at: .
        /// </summary>
        internal static string AutomationStartTime {
            get {
                return ResourceManager.GetString("AutomationStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build finish time: .
        /// </summary>
        internal static string BuildFinishTime {
            get {
                return ResourceManager.GetString("BuildFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building....
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build start time: .
        /// </summary>
        internal static string BuildStartTime {
            get {
                return ResourceManager.GetString("BuildStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up workspace....
        /// </summary>
        internal static string CleaningUpWorkspace {
            get {
                return ResourceManager.GetString("CleaningUpWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to TFS server....
        /// </summary>
        internal static string ConnectingToTfs {
            get {
                return ResourceManager.GetString("ConnectingToTfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying binaries to drop location....
        /// </summary>
        internal static string CopyingBinaries {
            get {
                return ResourceManager.GetString("CopyingBinaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying installer to drop location....
        /// </summary>
        internal static string CopyingInstaller {
            get {
                return ResourceManager.GetString("CopyingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying test automation cleanup file....
        /// </summary>
        internal static string CopyingTestAutomationCleanupFile {
            get {
                return ResourceManager.GetString("CopyingTestAutomationCleanupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying test automation settings file....
        /// </summary>
        internal static string CopyingTestAutomationSettingsFile {
            get {
                return ResourceManager.GetString("CopyingTestAutomationSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finish time: .
        /// </summary>
        internal static string DownloadFinishTime {
            get {
                return ResourceManager.GetString("DownloadFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download start time: .
        /// </summary>
        internal static string DownloadStartTime {
            get {
                return ResourceManager.GetString("DownloadStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest changeset number....
        /// </summary>
        internal static string GettingLatestChangesetNumber {
            get {
                return ResourceManager.GetString("GettingLatestChangesetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid URI is expected..
        /// </summary>
        internal static string InvalidUriException {
            get {
                return ResourceManager.GetString("InvalidUriException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changeset built: .
        /// </summary>
        internal static string LastChangesetBuilt {
            get {
                return ResourceManager.GetString("LastChangesetBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest changeset:.
        /// </summary>
        internal static string LatestChangesetNumber {
            get {
                return ResourceManager.GetString("LatestChangesetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new changeset available..
        /// </summary>
        internal static string NoNewChangesetAvailable {
            get {
                return ResourceManager.GetString("NoNewChangesetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the project : .
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have read permission for {1}.
        /// </summary>
        internal static string ReadPermissionException {
            get {
                return ResourceManager.GetString("ReadPermissionException", resourceCulture);
            }
        }
    }
}
