//*********************************************************
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
//
//
//
//
//
//*********************************************************

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bio.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence for the accession number {0} not found..
        /// </summary>
        internal static string AccessionSequenceNotFound {
            get {
                return ResourceManager.GetString("AccessionSequenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceAlphabet is null. Set it to correct alphabet!.
        /// </summary>
        internal static string ALPHABET_NULL {
            get {
                return ResourceManager.GetString("ALPHABET_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet in the specified sequence list does not have the same Alphabet..
        /// </summary>
        internal static string AlphabetMismatchInConstructor {
            get {
                return ResourceManager.GetString("AlphabetMismatchInConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add or replace with new sequence, Alphabet of the new sequence must match with the Alphabet of this SegmentedSequence..
        /// </summary>
        internal static string AlphabetMismatchInEdit {
            get {
                return ResourceManager.GetString("AlphabetMismatchInEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of aminoacids and weights should match.
        /// </summary>
        internal static string AminoAcidsAndWeightsShouldMatch {
            get {
                return ResourceManager.GetString("AminoAcidsAndWeightsShouldMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of range must be smaller than end..
        /// </summary>
        internal static string ARGUMENT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ARGUMENT_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure BLAST.
        /// </summary>
        internal static string AZURE_BLAST_NAME {
            get {
                return ResourceManager.GetString("AZURE_BLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM filename and Index filename can&apos;t be same..
        /// </summary>
        internal static string BAM_BAMFileNIndexFileContbeSame {
            get {
                return ResourceManager.GetString("BAM_BAMFileNIndexFileContbeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use this instance anymore as underlying stream is already disposed..
        /// </summary>
        internal static string BAM_CantUseBAMIndexStreamDisposed {
            get {
                return ResourceManager.GetString("BAM_CantUseBAMIndexStreamDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bam.
        /// </summary>
        internal static string BAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("BAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM format does not supports writing multiple ISequenceAlignment objects to a file..
        /// </summary>
        internal static string BAM_FormatMultipleAlignmentsNotSupported {
            get {
                return ResourceManager.GetString("BAM_FormatMultipleAlignmentsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM formatter does not support formatting to string..
        /// </summary>
        internal static string BAM_FormatStringNotSupported {
            get {
                return ResourceManager.GetString("BAM_FormatStringNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bai.
        /// </summary>
        internal static string BAM_INDEXFILEEXTENSION {
            get {
                return ResourceManager.GetString("BAM_INDEXFILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM file..
        /// </summary>
        internal static string BAM_InvalidBAMFile {
            get {
                return ResourceManager.GetString("BAM_InvalidBAMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CIGAR found..
        /// </summary>
        internal static string BAM_InvalidCIGAR {
            get {
                return ResourceManager.GetString("BAM_InvalidCIGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encoded sequence value.
        /// </summary>
        internal static string BAM_InvalidEncodedSequenceValue {
            get {
                return ResourceManager.GetString("BAM_InvalidEncodedSequenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BAM index file..
        /// </summary>
        internal static string BAM_InvalidIndexFile {
            get {
                return ResourceManager.GetString("BAM_InvalidIndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer value &quot;{0}&quot; found in optional field &quot;{1}&quot;..
        /// </summary>
        internal static string BAM_InvalidIntValueInOptField {
            get {
                return ResourceManager.GetString("BAM_InvalidIntValueInOptField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer value &quot;{0}&quot; found in optional field &quot;{1}&quot; of the alingned seq &quot;{2}&quot;..
        /// </summary>
        internal static string BAM_InvalidIntValueInOptFieldOfAlignedSeq {
            get {
                return ResourceManager.GetString("BAM_InvalidIntValueInOptFieldOfAlignedSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid optional valuetype.
        /// </summary>
        internal static string BAM_InvalidOptValType {
            get {
                return ResourceManager.GetString("BAM_InvalidOptValType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM.
        /// </summary>
        internal static string BAM_NAME {
            get {
                return ResourceManager.GetString("BAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference sequence name \&quot;{0}\&quot; not found..
        /// </summary>
        internal static string BAM_RefSeqNotFound {
            get {
                return ResourceManager.GetString("BAM_RefSeqNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM parser does not supports reading from a text reader..
        /// </summary>
        internal static string BAM_TextreaderNotSupportedMessage {
            get {
                return ResourceManager.GetString("BAM_TextreaderNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM formatter does not support writing to text writer..
        /// </summary>
        internal static string BAM_TextWriterNotSupported {
            get {
                return ResourceManager.GetString("BAM_TextWriterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read compressed block.
        /// </summary>
        internal static string BAM_UnableToReadCompressedBlock {
            get {
                return ResourceManager.GetString("BAM_UnableToReadCompressedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a SequenceAlignmentMap to a particular location, usually a file. 
        ///The output is formatted according to the BAM file format..
        /// </summary>
        internal static string BAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BAMParser reads from a source of binary data that is formatted according to the BAM 
        ///file specification, and converts the data to in-memory SequenceAlignmentMap object..
        /// </summary>
        internal static string BAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet can&apos;t be set as BAM supports only DNA alphabet..
        /// </summary>
        internal static string BAMParserAlphabetCantBeSet {
            get {
                return ResourceManager.GetString("BAMParserAlphabetCantBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlastXmlParser.Parse: No records were found in the input..
        /// </summary>
        internal static string BlastNoRecords {
            get {
                return ResourceManager.GetString("BlastNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bases to be extended before stopping alignment.
        /// </summary>
        internal static string BREAK_LENGTH_DESCRIPTION {
            get {
                return ResourceManager.GetString("BREAK_LENGTH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Length.
        /// </summary>
        internal static string BREAK_LENGTH_NAME {
            get {
                return ResourceManager.GetString("BREAK_LENGTH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Complement builder (char array) has incorrect length. Should be equal to sequence length.
        /// </summary>
        internal static string BuilderIncorrectLength {
            get {
                return ResourceManager.GetString("BuilderIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add null to SegmentedSequence.
        /// </summary>
        internal static string CannotAddNullSequence {
            get {
                return ResourceManager.GetString("CannotAddNullSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequences at index {0} and {1} of the underlying sequence list are refer to a same sequence instance thus cannot continue with this operation..
        /// </summary>
        internal static string CannotContinueWithRemove {
            get {
                return ResourceManager.GetString("CannotContinueWithRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not modify a read only sequence.
        /// </summary>
        internal static string CanNotModifyReadonlySequence {
            get {
                return ResourceManager.GetString("CanNotModifyReadonlySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustal file has unknown sequence {0}.
        /// </summary>
        internal static string ClustalUnknownSequence {
            get {
                return ResourceManager.GetString("ClustalUnknownSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aln.
        /// </summary>
        internal static string CLUSTALW_FILEEXTENSION {
            get {
                return ResourceManager.GetString("CLUSTALW_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClustalW.
        /// </summary>
        internal static string CLUSTALW_NAME {
            get {
                return ResourceManager.GetString("CLUSTALW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ClustalWParser reads from a source of text that is formatted according to the ClustalW flat file specification, and converts the data to in-memory ISequenceAlignment objects.  For advanced users, the ability to select an encoding for the internal memory representation is provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string CLUSTALWPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("CLUSTALWPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location with Complement operator cannot contain more than one sub locations..
        /// </summary>
        internal static string ComplementWithMorethanOneSubLocs {
            get {
                return ResourceManager.GetString("ComplementWithMorethanOneSubLocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data virtualization needs to be enabled with proper file name..
        /// </summary>
        internal static string DataVirtualizationNeedsInputFile {
            get {
                return ResourceManager.GetString("DataVirtualizationNeedsInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Virtualization is not enabled and this property cannot be set..
        /// </summary>
        internal static string DataVirtualizationPropertyCannotBeSet {
            get {
                return ResourceManager.GetString("DataVirtualizationPropertyCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Virtualization is enbled and this property cannot be 0 or less..
        /// </summary>
        internal static string DataVirtualizationPropertyInvalidSet {
            get {
                return ResourceManager.GetString("DataVirtualizationPropertyInvalidSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate SQ header found for {0}..
        /// </summary>
        internal static string DuplicateSQHeader {
            get {
                return ResourceManager.GetString("DuplicateSQHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate read found. Id:{0}.
        /// </summary>
        internal static string DuplicatingReadIds {
            get {
                return ResourceManager.GetString("DuplicatingReadIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBI WU-BLAST.
        /// </summary>
        internal static string EBIWUBLAST_NAME {
            get {
                return ResourceManager.GetString("EBIWUBLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service response was empty. Request: {0}..
        /// </summary>
        internal static string EMPTYRESPONSE {
            get {
                return ResourceManager.GetString("EMPTYRESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndData can not be null or empty..
        /// </summary>
        internal static string EndDataCannotBeNull {
            get {
                return ResourceManager.GetString("EndDataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .fa,.mpfa,.fna,.faa,.fsa,.fas,.fasta.
        /// </summary>
        internal static string FASTA_FILEEXTENSION {
            get {
                return ResourceManager.GetString("FASTA_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasta.
        /// </summary>
        internal static string FASTA_NAME {
            get {
                return ResourceManager.GetString("FASTA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an ISequence to a particular location, usually a file. The output is formatted
        ///according to the GenBank file format. .
        /// </summary>
        internal static string FASTAFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTAFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FastaParser reads from a source of text that is formatted according to the FASTA flat
        ///file specification, and converts the data to in-memory ISequence objects.  For advanced
        ///users, the ability to select an encoding for the internal memory representation is
        ///provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string FASTAPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTAPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality score line is empty for the sequence Id: {0}.
        /// </summary>
        internal static string FastQ_EmptyQualityScoreLine {
            get {
                return ResourceManager.GetString("FastQ_EmptyQualityScoreLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .fq,.fastq.
        /// </summary>
        internal static string FASTQ_FILEEXTENSION {
            get {
                return ResourceManager.GetString("FASTQ_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality scores header does not match with sequence header for the sequence Id: {0}.
        /// </summary>
        internal static string FastQ_InvalidQualityScoreHeaderData {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoreHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file or data stream is missing &quot;+&quot; in the quality score header line for the sequence Id: {0}.
        /// </summary>
        internal static string FastQ_InvalidQualityScoreHeaderLine {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoreHeaderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of quality scores and sequence symbols are not same for the sequence Id: {0}.
        /// </summary>
        internal static string FastQ_InvalidQualityScoresLength {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoresLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastQ formatter can format IQualitativeSequence instances only..
        /// </summary>
        internal static string FastQ_InvalidSequence {
            get {
                return ResourceManager.GetString("FastQ_InvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence data line is empty for the sequence Id: {0}.
        /// </summary>
        internal static string FastQ_InvalidSequenceLine {
            get {
                return ResourceManager.GetString("FastQ_InvalidSequenceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastQ.
        /// </summary>
        internal static string FASTQ_NAME {
            get {
                return ResourceManager.GetString("FASTQ_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an IQualitativeSequence to a particular location, usually a file. The output is formatted according to the FASTQ file format..
        /// </summary>
        internal static string FASTQFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FastQParser reads from a source of text that is formatted according to the FASTQ file specification, and converts the data to in-memory IQualitativeSequence objects..
        /// </summary>
        internal static string FASTQPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First input sequence alphabet does not match similarity matrix alphabet..
        /// </summary>
        internal static string FirstInputSequenceMismatchSimilarityMatrix {
            get {
                return ResourceManager.GetString("FirstInputSequenceMismatchSimilarityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum fixed diagonal difference.
        /// </summary>
        internal static string FIXED_SEPARATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("FIXED_SEPARATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Separation.
        /// </summary>
        internal static string FIXED_SEPARATION_NAME {
            get {
                return ResourceManager.GetString("FIXED_SEPARATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Read is empty.
        /// </summary>
        internal static string ForwardReadCount {
            get {
                return ResourceManager.GetString("ForwardReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of inserting a gap character.
        /// </summary>
        internal static string GAP_COST_DESCRIPTION {
            get {
                return ResourceManager.GetString("GAP_COST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Cost.
        /// </summary>
        internal static string GAP_COST_NAME {
            get {
                return ResourceManager.GetString("GAP_COST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of extending an already existing gap.
        /// </summary>
        internal static string GAP_EXTENSION_COST_DESCRIPTION {
            get {
                return ResourceManager.GetString("GAP_EXTENSION_COST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap Extension Cost.
        /// </summary>
        internal static string GAP_EXTENSION_COST_NAME {
            get {
                return ResourceManager.GetString("GAP_EXTENSION_COST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gb,.gbk,.genbank.
        /// </summary>
        internal static string GENBANK_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GENBANK_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenBank.
        /// </summary>
        internal static string GENBANK_NAME {
            get {
                return ResourceManager.GetString("GENBANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected empty feature key..
        /// </summary>
        internal static string GenbankEmptyFeature {
            get {
                return ResourceManager.GetString("GenbankEmptyFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an ISequence to a particular location, usually a file. The output is formatted
        ///according to the GenBank file format. A method is also provided for quickly accessing
        ///the content in string form for applications that do not need to first write to file..
        /// </summary>
        internal static string GENBANKFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid feature line: {0}..
        /// </summary>
        internal static string GenbankInvalidFeature {
            get {
                return ResourceManager.GetString("GenbankInvalidFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GenBankParser reads from a source of text that is formatted according to the GenBank flat
        ///file specification, and converts the data to in-memory ISequence objects.  For advanced
        ///users, the ability to select an encoding for the internal memory representation is
        ///provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string GENBANKPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gff.
        /// </summary>
        internal static string GFF_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GFF_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFF.
        /// </summary>
        internal static string GFF_NAME {
            get {
                return ResourceManager.GetString("GFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes an ISequence to a particular location, usually a file. The output is formatted
        ///according to the GFF file format. A method is also provided for quickly accessing
        ///the content in string form for applications that do not need to first write to file..
        /// </summary>
        internal static string GFFFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} field: {1}..
        /// </summary>
        internal static string GffInvalidField {
            get {
                return ResourceManager.GetString("GffInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence line: {0}..
        /// </summary>
        internal static string GffInvalidSequence {
            get {
                return ResourceManager.GetString("GffInvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFF file contains no features..
        /// </summary>
        internal static string GFFNoFeatures {
            get {
                return ResourceManager.GetString("GFFNoFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GffParser reads from a source of text that is formatted according to the GFF flat
        ///file specification, and converts the data to in-memory ISequence objects.  For advanced
        ///users, the ability to select an encoding for the internal memory representation is
        ///provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string GFFPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported GFF version: {0}..
        /// </summary>
        internal static string GffUnsupportedVersion {
            get {
                return ResourceManager.GetString("GffUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.
        /// </summary>
        internal static string IndexParameterName {
            get {
                return ResourceManager.GetString("IndexParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sequences use different alphabets..
        /// </summary>
        internal static string InputAlphabetsMismatch {
            get {
                return ResourceManager.GetString("InputAlphabetsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of input sequence should be greater than Length of MUM ({0})..
        /// </summary>
        internal static string InputSequenceMustBeGreaterThanMUM {
            get {
                return ResourceManager.GetString("InputSequenceMustBeGreaterThanMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad input in {0} file..
        /// </summary>
        internal static string INVAILD_INPUT_FILE {
            get {
                return ResourceManager.GetString("INVAILD_INPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol {0} is not a valid {1} symbol.
        /// </summary>
        internal static string INVALID_SYMBOL {
            get {
                return ResourceManager.GetString("INVALID_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified encoding &quot;{0}&quot; is not valid for the {1} Alphabet..
        /// </summary>
        internal static string InvalidEncodingForAlphabet {
            get {
                return ResourceManager.GetString("InvalidEncodingForAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid end data: {0}.
        /// </summary>
        internal static string InvalidEndData {
            get {
                return ResourceManager.GetString("InvalidEndData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and length do not denote a valid range of elements in the sequence.
        /// </summary>
        internal static string InvalidIndexAndLength {
            get {
                return ResourceManager.GetString("InvalidIndexAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node does not have valid Kmer index information.
        /// </summary>
        internal static string InvalidKmerIndex {
            get {
                return ResourceManager.GetString("InvalidKmerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters in the sequence and number of bytes in the qualScores are must be equal..
        /// </summary>
        internal static string InvalidLength_Sequence_QualScores {
            get {
                return ResourceManager.GetString("InvalidLength_Sequence_QualScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid location string {0}..
        /// </summary>
        internal static string InvalidLocationString {
            get {
                return ResourceManager.GetString("InvalidLocationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid optional field: {0}..
        /// </summary>
        internal static string InvalidOptionalField {
            get {
                return ResourceManager.GetString("InvalidOptionalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value is not belongs to the specified encoding..
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}: &quot;{1}&quot;. The allowed pattern is: {2}..
        /// </summary>
        internal static string InvalidPatternMessage {
            get {
                return ResourceManager.GetString("InvalidPatternMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position and length do not denote a valid range of elements in the sequence.
        /// </summary>
        internal static string InvalidPositionAndLength {
            get {
                return ResourceManager.GetString("InvalidPositionAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QName value. Maximum allowed length for QName value is 254 characters..
        /// </summary>
        internal static string InvalidQNameLength {
            get {
                return ResourceManager.GetString("InvalidQNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quality score: {0}.
        /// </summary>
        internal static string InvalidQualityScore {
            get {
                return ResourceManager.GetString("InvalidQualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}: &quot;{1}&quot;. The allowed range is {2} to {3}..
        /// </summary>
        internal static string InvalidRangeMessage {
            get {
                return ResourceManager.GetString("InvalidRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet of {0} sequence is invalid..
        /// </summary>
        internal static string InvalidReferredAlphabet {
            get {
                return ResourceManager.GetString("InvalidReferredAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameter: Only int, float, and stringList supported..
        /// </summary>
        internal static string InvalidSearchParameter {
            get {
                return ResourceManager.GetString("InvalidSearchParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid separator {0}.
        /// </summary>
        internal static string InvalidSeparator {
            get {
                return ResourceManager.GetString("InvalidSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and length do not denote a valid range of elements in the sequence.
        /// </summary>
        internal static string InvalidStartAndLength {
            get {
                return ResourceManager.GetString("InvalidStartAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start data: {0}.
        /// </summary>
        internal static string InvalidStartData {
            get {
                return ResourceManager.GetString("InvalidStartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start position must be less than or equal to the end position..
        /// </summary>
        internal static string InvalidStartNEndPositions {
            get {
                return ResourceManager.GetString("InvalidStartNEndPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize symbol: {0}.
        /// </summary>
        internal static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not recognize one or more symbol in the sequence: {0}.
        /// </summary>
        internal static string InvalidSymbolInString {
            get {
                return ResourceManager.GetString("InvalidSymbolInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type format: {0}..
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obj is not an IndexedItem&lt;T&gt;.
        /// </summary>
        internal static string InvalidTypeIndexedItem {
            get {
                return ResourceManager.GetString("InvalidTypeIndexedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obj is not an IndexedSequenceItem.
        /// </summary>
        internal static string InvalidTypeIndexedSequenceItem {
            get {
                return ResourceManager.GetString("InvalidTypeIndexedSequenceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Format error - {1}.
        /// </summary>
        internal static string IOFormatErrorMessage {
            get {
                return ResourceManager.GetString("IOFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text to parse in the specified input file or data stream..
        /// </summary>
        internal static string IONoTextToParse {
            get {
                return ResourceManager.GetString("IONoTextToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists.
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer sequence index is out of range for node.
        /// </summary>
        internal static string KmerIndexOutOfRange {
            get {
                return ResourceManager.GetString("KmerIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer Length is larger than the sequence length.
        /// </summary>
        internal static string KmerLengthIsTooLong {
            get {
                return ResourceManager.GetString("KmerLengthIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer Length needs to be a positive value.
        /// </summary>
        internal static string KmerLengthShouldBePositive {
            get {
                return ResourceManager.GetString("KmerLengthShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmer position or length is out of range for node.
        /// </summary>
        internal static string KmerPositionOutOfRange {
            get {
                return ResourceManager.GetString("KmerPositionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum legnth of Maximal Unique Match.
        /// </summary>
        internal static string LENGTH_OF_MUM_DESCRIPTION {
            get {
                return ResourceManager.GetString("LENGTH_OF_MUM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of MUM.
        /// </summary>
        internal static string LENGTH_OF_MUM_NAME {
            get {
                return ResourceManager.GetString("LENGTH_OF_MUM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library doesn&apos;t exist.
        /// </summary>
        internal static string LibraryExist {
            get {
                return ResourceManager.GetString("LibraryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library - Invalid Parameters.
        /// </summary>
        internal static string LibraryInvalidParameters {
            get {
                return ResourceManager.GetString("LibraryInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty. Should contain atleast one element!.
        /// </summary>
        internal static string LIST_EMPTY {
            get {
                return ResourceManager.GetString("LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bio.log.
        /// </summary>
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory tag {0} is not found for the record type {1}..
        /// </summary>
        internal static string MandatoryTagNotFound {
            get {
                return ResourceManager.GetString("MandatoryTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum seperation between the adjacent matches in clusters.
        /// </summary>
        internal static string MAXIMUM_SEPARATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("MAXIMUM_SEPARATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Separation.
        /// </summary>
        internal static string MAXIMUM_SEPARATION_NAME {
            get {
                return ResourceManager.GetString("MAXIMUM_SEPARATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum output score.
        /// </summary>
        internal static string MINIMUM_SCORE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MINIMUM_SCORE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Score.
        /// </summary>
        internal static string MINIMUM_SCORE_NAME {
            get {
                return ResourceManager.GetString("MINIMUM_SCORE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum two sequences are required to run alignment..
        /// </summary>
        internal static string MinimumTwoSequences {
            get {
                return ResourceManager.GetString("MinimumTwoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of MUM cannot be less than 1..
        /// </summary>
        internal static string MUMLengthTooSmall {
            get {
                return ResourceManager.GetString("MUMLengthTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUMmer 3.0.
        /// </summary>
        internal static string MUMMER3 {
            get {
                return ResourceManager.GetString("MUMMER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise global alignment.
        /// </summary>
        internal static string MUMMER3DESC {
            get {
                return ResourceManager.GetString("MUMMER3DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUMmer currently runs only with Needleman-Wunsch / Smith-Waterman algorithms..
        /// </summary>
        internal static string MUMmerIncompatibleAligner {
            get {
                return ResourceManager.GetString("MUMmerIncompatibleAligner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCBI QBLAST.
        /// </summary>
        internal static string NCBIQBLAST_NAME {
            get {
                return ResourceManager.GetString("NCBIQBLAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise global alignment.
        /// </summary>
        internal static string NEEDLEMAN_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEEDLEMAN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needleman-Wunsch.
        /// </summary>
        internal static string NEEDLEMAN_NAME {
            get {
                return ResourceManager.GetString("NEEDLEMAN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt, .tre, .newick.
        /// </summary>
        internal static string NEWICK_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("NEWICK_FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a PhylogeneticTree to a particular location, usually a file. The output is formatted
        ///according to the Newick format..
        /// </summary>
        internal static string NEWICK_FORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEWICK_FORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newick.
        /// </summary>
        internal static string NEWICK_NAME {
            get {
                return ResourceManager.GetString("NEWICK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads from a source of text that is formatted according to the Newick flat
        ///file specification, and converts the data to in-memory PhylogeneticTree object..
        /// </summary>
        internal static string NEWICK_PARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEWICK_PARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nxs,.nex.
        /// </summary>
        internal static string NEXUS_FILEEXTENSION {
            get {
                return ResourceManager.GetString("NEXUS_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus.
        /// </summary>
        internal static string NEXUS_NAME {
            get {
                return ResourceManager.GetString("NEXUS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A NexusParser reads from a source of text that is formatted according to the Nexus flat file specification, and converts the data to in-memory ISequenceAlignment objects.  For advanced users, the ability to select an encoding for the internal memory representation is provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string NEXUSPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEXUSPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location with None operator can not contain sub locations..
        /// </summary>
        internal static string NoneWithSubLocs {
            get {
                return ResourceManager.GetString("NoneWithSubLocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported in BasicDerivedSequence.
        /// </summary>
        internal static string NotSupportedBasicDerivedSequence {
            get {
                return ResourceManager.GetString("NotSupportedBasicDerivedSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported in VirtualSequence.
        /// </summary>
        internal static string NotSupportedInVirtualSequence {
            get {
                return ResourceManager.GetString("NotSupportedInVirtualSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported in SparseSequence.
        /// </summary>
        internal static string NotSupportedSparseSequence {
            get {
                return ResourceManager.GetString("NotSupportedSparseSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ntax does not match the number of IDs..
        /// </summary>
        internal static string NtaxMismatch {
            get {
                return ResourceManager.GetString("NtaxMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of nucleoties and weights should match.
        /// </summary>
        internal static string NucleotidesAndWeightsShouldMatch {
            get {
                return ResourceManager.GetString("NucleotidesAndWeightsShouldMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUCmer 3.0.
        /// </summary>
        internal static string NUCMER3 {
            get {
                return ResourceManager.GetString("NUCMER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise local alignment.
        /// </summary>
        internal static string NUCMER3DESC {
            get {
                return ResourceManager.GetString("NUCMER3DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationBuilder can not be null.
        /// </summary>
        internal static string NullLocationBuild {
            get {
                return ResourceManager.GetString("NullLocationBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver can not be null.
        /// </summary>
        internal static string NullResolver {
            get {
                return ResourceManager.GetString("NullResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only DNA &amp; RNA sequences can be passed as input to {0}..
        /// </summary>
        internal static string OnlyDNAOrRNAInput {
            get {
                return ResourceManager.GetString("OnlyDNAOrRNAInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out-of-spec SOURCE.
        /// </summary>
        internal static string OutOfSpec {
            get {
                return ResourceManager.GetString("OutOfSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise global alignment.
        /// </summary>
        internal static string PAIRWISE_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAIRWISE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise-Overlap.
        /// </summary>
        internal static string PAIRWISE_NAME {
            get {
                return ResourceManager.GetString("PAIRWISE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise Alignment expected 2 input sequences, received {0}..
        /// </summary>
        internal static string PairwiseAlignerWrongArgumentCount {
            get {
                return ResourceManager.GetString("PairwiseAlignerWrongArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter name {0}..
        /// </summary>
        internal static string PARAMETER_UNKNOWN {
            get {
                return ResourceManager.GetString("PARAMETER_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value {0} for parameter {0}..
        /// </summary>
        internal static string PARAMETER_VALUE_INVALID {
            get {
                return ResourceManager.GetString("PARAMETER_VALUE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument contains a null value..
        /// </summary>
        internal static string ParameterContainsNullValue {
            get {
                return ResourceManager.GetString("ParameterContainsNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was empty..
        /// </summary>
        internal static string ParameterEmpty {
            get {
                return ResourceManager.GetString("ParameterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter item must be of type AminoAcid.
        /// </summary>
        internal static string ParameterItemMustBeAminoAcid {
            get {
                return ResourceManager.GetString("ParameterItemMustBeAminoAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter item must be of type Nucleotide.
        /// </summary>
        internal static string ParameterItemMustBeNucleotide {
            get {
                return ResourceManager.GetString("ParameterItemMustBeNucleotide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range it must be non negative and less than the count of this sequence..
        /// </summary>
        internal static string ParameterMustLessThanCount {
            get {
                return ResourceManager.GetString("ParameterMustLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range it must be non negative and less than or equal to the count of this sequence..
        /// </summary>
        internal static string ParameterMustLessThanOrEqualToCount {
            get {
                return ResourceManager.GetString("ParameterMustLessThanOrEqualToCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was out of the range it must be non negative..
        /// </summary>
        internal static string ParameterMustNonNegative {
            get {
                return ResourceManager.GetString("ParameterMustNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alphabet.
        /// </summary>
        internal static string ParameterNameAlphabet {
            get {
                return ResourceManager.GetString("ParameterNameAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aminoacids.
        /// </summary>
        internal static string ParameterNameAminoAcids {
            get {
                return ResourceManager.GetString("ParameterNameAminoAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        internal static string ParameterNameArray {
            get {
                return ResourceManager.GetString("ParameterNameArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encoding.
        /// </summary>
        internal static string ParameterNameEncoding {
            get {
                return ResourceManager.GetString("ParameterNameEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endPos.
        /// </summary>
        internal static string ParameterNameEndPos {
            get {
                return ResourceManager.GetString("ParameterNameEndPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iContig.
        /// </summary>
        internal static string ParameterNameiContig {
            get {
                return ResourceManager.GetString("ParameterNameiContig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.
        /// </summary>
        internal static string ParameterNameIndex {
            get {
                return ResourceManager.GetString("ParameterNameIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string ParameterNameItem {
            get {
                return ResourceManager.GetString("ParameterNameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        internal static string ParameterNameLength {
            get {
                return ResourceManager.GetString("ParameterNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string ParameterNameLocation {
            get {
                return ResourceManager.GetString("ParameterNameLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nucleotides.
        /// </summary>
        internal static string ParameterNameNucleotides {
            get {
                return ResourceManager.GetString("ParameterNameNucleotides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        internal static string ParameterNamePosition {
            get {
                return ResourceManager.GetString("ParameterNamePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qualScore.
        /// </summary>
        internal static string ParameterNameQualScore {
            get {
                return ResourceManager.GetString("ParameterNameQualScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qualScores.
        /// </summary>
        internal static string ParameterNameQualScores {
            get {
                return ResourceManager.GetString("ParameterNameQualScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qualSequence.
        /// </summary>
        internal static string ParameterNameQualSequence {
            get {
                return ResourceManager.GetString("ParameterNameQualSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string ParameterNameQuery {
            get {
                return ResourceManager.GetString("ParameterNameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sequence.
        /// </summary>
        internal static string ParameterNameSequence {
            get {
                return ResourceManager.GetString("ParameterNameSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sequenceAlignment.
        /// </summary>
        internal static string ParameterNameSequenceAlignment {
            get {
                return ResourceManager.GetString("ParameterNameSequenceAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sequenceItems.
        /// </summary>
        internal static string ParameterNameSequenceItems {
            get {
                return ResourceManager.GetString("ParameterNameSequenceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sequences.
        /// </summary>
        internal static string ParameterNameSequences {
            get {
                return ResourceManager.GetString("ParameterNameSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string ParameterNameSize {
            get {
                return ResourceManager.GetString("ParameterNameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.
        /// </summary>
        internal static string ParameterNameSource {
            get {
                return ResourceManager.GetString("ParameterNameSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string ParameterNameStart {
            get {
                return ResourceManager.GetString("ParameterNameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startPos.
        /// </summary>
        internal static string ParameterNameStartPos {
            get {
                return ResourceManager.GetString("ParameterNameStartPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string ParameterNameValue {
            get {
                return ResourceManager.GetString("ParameterNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weights.
        /// </summary>
        internal static string ParameterNameWeights {
            get {
                return ResourceManager.GetString("ParameterNameWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writer.
        /// </summary>
        internal static string ParameterNameWriter {
            get {
                return ResourceManager.GetString("ParameterNameWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified argument was not known by the Alpabet of this sequence..
        /// </summary>
        internal static string ParameterNotKnownByAlphabet {
            get {
                return ResourceManager.GetString("ParameterNotKnownByAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid header..
        /// </summary>
        internal static string ParseHeaderError {
            get {
                return ResourceManager.GetString("ParseHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text to parse..
        /// </summary>
        internal static string Parser_NoTextErrorMessage {
            get {
                return ResourceManager.GetString("Parser_NoTextErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect alphabet set by user..
        /// </summary>
        internal static string ParserIncorrectAlphabet {
            get {
                return ResourceManager.GetString("ParserIncorrectAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format: {0}..
        /// </summary>
        internal static string ParserInvalidDate {
            get {
                return ResourceManager.GetString("ParserInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown LOCUS format: {0}..
        /// </summary>
        internal static string ParserInvalidLocus {
            get {
                return ResourceManager.GetString("ParserInvalidLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reference field name: {0}..
        /// </summary>
        internal static string ParserInvalidReferenceField {
            get {
                return ResourceManager.GetString("ParserInvalidReferenceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source field name: {0}..
        /// </summary>
        internal static string ParserInvalidSourceField {
            get {
                return ResourceManager.GetString("ParserInvalidSourceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid strand topology: {0}..
        /// </summary>
        internal static string ParserInvalidStrand {
            get {
                return ResourceManager.GetString("ParserInvalidStrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in PRIMARY line: {0}..
        /// </summary>
        internal static string ParserPrimaryLineError {
            get {
                return ResourceManager.GetString("ParserPrimaryLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data after REFERENCE should start with reference number: {0}..
        /// </summary>
        internal static string ParserReferenceError {
            get {
                return ResourceManager.GetString("ParserReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second locus encountered {0}..
        /// </summary>
        internal static string ParserSecondLocus {
            get {
                return ResourceManager.GetString("ParserSecondLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected line within sequence data: {0}..
        /// </summary>
        internal static string ParserUnexpectedLineInSequence {
            get {
                return ResourceManager.GetString("ParserUnexpectedLineInSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .phy,.ph.
        /// </summary>
        internal static string PHYLIP_FILEEXTENSION {
            get {
                return ResourceManager.GetString("PHYLIP_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phylip.
        /// </summary>
        internal static string PHYLIP_NAME {
            get {
                return ResourceManager.GetString("PHYLIP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PhylipParser reads from a source of text that is formatted according to the Phylip flat file specification, and converts the data to in-memory ISequenceAlignment objects.  For advanced users, the ability to select an encoding for the internal memory representation is provided. There is also a default encoding for each alphabet that may be encountered..
        /// </summary>
        internal static string PHYLIPPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("PHYLIPPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query sequence list cannot be null.
        /// </summary>
        internal static string QueryListCannotBeNull {
            get {
                return ResourceManager.GetString("QueryListCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query sequence cannot be null..
        /// </summary>
        internal static string QuerySequenceCannotBeNull {
            get {
                return ResourceManager.GetString("QuerySequenceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify a read-only collection..
        /// </summary>
        internal static string READ_ONLY_COLLECTION_MESSAGE {
            get {
                return ResourceManager.GetString("READ_ONLY_COLLECTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the reads in input list is null.
        /// </summary>
        internal static string ReadCannotBeNull {
            get {
                return ResourceManager.GetString("ReadCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read is empty.
        /// </summary>
        internal static string ReadCount {
            get {
                return ResourceManager.GetString("ReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference sequence list cannot be null..
        /// </summary>
        internal static string ReferenceListCannotBeNull {
            get {
                return ResourceManager.GetString("ReferenceListCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference sequence cannot be null.
        /// </summary>
        internal static string ReferenceSequenceCannotBeNull {
            get {
                return ResourceManager.GetString("ReferenceSequenceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse sequences which contains &apos;=&apos; symbol without the reference sequence..
        /// </summary>
        internal static string RefSequenceNofFound {
            get {
                return ResourceManager.GetString("RefSequenceNofFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In Loading Issue on {0} , Instance : {1}.
        /// </summary>
        internal static string REGISTRATION_LOADING_ERROR {
            get {
                return ResourceManager.GetString("REGISTRATION_LOADING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Read is empty.
        /// </summary>
        internal static string ReverseReadCount {
            get {
                return ResourceManager.GetString("ReverseReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header is missing in one of the aligned sequence in specified sequenceAlignment object..
        /// </summary>
        internal static string SAM_AlignedSequenceHeaderMissing {
            get {
                return ResourceManager.GetString("SAM_AlignedSequenceHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment header not found..
        /// </summary>
        internal static string SAM_AlignmentHeaderMissing {
            get {
                return ResourceManager.GetString("SAM_AlignmentHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sam.
        /// </summary>
        internal static string SAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("SAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM format does not supports writing multiple ISequenceAlignment objects to a file..
        /// </summary>
        internal static string SAM_FormatMultipleAlignmentsNotSupported {
            get {
                return ResourceManager.GetString("SAM_FormatMultipleAlignmentsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM.
        /// </summary>
        internal static string SAM_NAME {
            get {
                return ResourceManager.GetString("SAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMAlignedSequenceHeader not found.
        /// </summary>
        internal static string SAMAlignedSequenceHeaderNotFound {
            get {
                return ResourceManager.GetString("SAMAlignedSequenceHeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMAlignmentHeader not found.
        /// </summary>
        internal static string SAMAlignmentHeaderNotFound {
            get {
                return ResourceManager.GetString("SAMAlignmentHeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a SequenceAlignmentMap to a particular location, usually a file. The output is formatted
        ///according to the SAM file format..
        /// </summary>
        internal static string SAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM only supports DNA aplhabet..
        /// </summary>
        internal static string SAMFormatterSupportsDNAOnly {
            get {
                return ResourceManager.GetString("SAMFormatterSupportsDNAOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SAMParser reads from a source of text that is formatted according to the SAM 
        ///file specification, and converts the data to in-memory SequenceAlignmentMap objects..
        /// </summary>
        internal static string SAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet can&apos;t be set as SAM supports only DNA alphabet..
        /// </summary>
        internal static string SAMParserAlphabetCantBeSet {
            get {
                return ResourceManager.GetString("SAMParserAlphabetCantBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second input sequence alphabet does not match similarity matrix alphabet..
        /// </summary>
        internal static string SecondInputSequenceMismatchSimilarityMatrix {
            get {
                return ResourceManager.GetString("SecondInputSequenceMismatchSimilarityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation factor.
        /// </summary>
        internal static string SEPARATION_FACTOR_DESCRIPTION {
            get {
                return ResourceManager.GetString("SEPARATION_FACTOR_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separation Factor.
        /// </summary>
        internal static string SEPARATION_FACTOR_NAME {
            get {
                return ResourceManager.GetString("SEPARATION_FACTOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequences are of different alphabet type in the alignment..
        /// </summary>
        internal static string SequenceAlphabetMismatch {
            get {
                return ResourceManager.GetString("SequenceAlphabetMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence should not be null.
        /// </summary>
        internal static string SequenceCannotBeNull {
            get {
                return ResourceManager.GetString("SequenceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sequence in alignment do not match the actual count..
        /// </summary>
        internal static string SequenceCountMismatch {
            get {
                return ResourceManager.GetString("SequenceCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence length does not match..
        /// </summary>
        internal static string SequenceLengthMismatch {
            get {
                return ResourceManager.GetString("SequenceLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence length in alignment do not match the actual length..
        /// </summary>
        internal static string SequenceLengthsMismatch {
            get {
                return ResourceManager.GetString("SequenceLengthsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End index of SequenceRange cannot be lesser than start index.
        /// </summary>
        internal static string SequenceRangeEndError {
            get {
                return ResourceManager.GetString("SequenceRangeEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceRange start and end cannot be set to negative numbers.
        /// </summary>
        internal static string SequenceRangeNonNegative {
            get {
                return ResourceManager.GetString("SequenceRangeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index of SequenceRange cannot be greater than end index.
        /// </summary>
        internal static string SequenceRangeStartError {
            get {
                return ResourceManager.GetString("SequenceRangeStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebServiceHandlers.dll.
        /// </summary>
        internal static string SERVICE_HANDLER_ASSEMBLY {
            get {
                return ResourceManager.GetString("SERVICE_HANDLER_ASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes matrix that determines the score for any possible pair of symbols.
        /// </summary>
        internal static string SIMILARITY_MATRIX_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMILARITY_MATRIX_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Matrix.
        /// </summary>
        internal static string SIMILARITY_MATRIX_NAME {
            get {
                return ResourceManager.GetString("SIMILARITY_MATRIX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligner Default.
        /// </summary>
        internal static string SimilarityMatrix_AutoDetectString {
            get {
                return ResourceManager.GetString("SimilarityMatrix_AutoDetectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityMatrix from file or stream. Bad or missing value in line {0}, exception {1}..
        /// </summary>
        internal static string SimilarityMatrix_BadOrMissingValue {
            get {
                return ResourceManager.GetString("SimilarityMatrix_BadOrMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal (Match x Mismatch).
        /// </summary>
        internal static string SimilarityMatrix_DiagonalSM {
            get {
                return ResourceManager.GetString("SimilarityMatrix_DiagonalSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityMatrix from file or stream. Fewer matrix line than needed..
        /// </summary>
        internal static string SimilarityMatrix_FewerMatrixLines {
            get {
                return ResourceManager.GetString("SimilarityMatrix_FewerMatrixLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityMatrix from file or stream. Invalid molecule type {0} in similarity matrix file..
        /// </summary>
        internal static string SimilarityMatrix_InvalidMoleculeType {
            get {
                return ResourceManager.GetString("SimilarityMatrix_InvalidMoleculeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityMatrix from file or stream. Missing name (first line)..
        /// </summary>
        internal static string SimilarityMatrix_NameMissing {
            get {
                return ResourceManager.GetString("SimilarityMatrix_NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimilarityMatrix from file or stream. Missing second line..
        /// </summary>
        internal static string SimilarityMatrix_SecondLineMissing {
            get {
                return ResourceManager.GetString("SimilarityMatrix_SecondLineMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity Matrix cannot be null..
        /// </summary>
        internal static string SimilarityMatrixCannotBeNull {
            get {
                return ResourceManager.GetString("SimilarityMatrixCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements a simple greedy assembly algorithm for DNA..
        /// </summary>
        internal static string SIMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple-Sequence.
        /// </summary>
        internal static string SIMPLE_NAME {
            get {
                return ResourceManager.GetString("SIMPLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic SNP Parser that uses XSV format.
        /// </summary>
        internal static string SIMPLE_SNP_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tsv.
        /// </summary>
        internal static string SIMPLE_SNP_FILEEXTENSION {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_FILEEXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic SNP.
        /// </summary>
        internal static string SIMPLE_SNP_NAME {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise local alignment.
        /// </summary>
        internal static string SMITH_DESCRIPTION {
            get {
                return ResourceManager.GetString("SMITH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith-Waterman.
        /// </summary>
        internal static string SMITH_NAME {
            get {
                return ResourceManager.GetString("SMITH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the maximum value of an integer..
        /// </summary>
        internal static string SparseSequenceConstructorIndexOutofRange {
            get {
                return ResourceManager.GetString("SparseSequenceConstructorIndexOutofRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ header is missing for {0}..
        /// </summary>
        internal static string SQHeaderMissing {
            get {
                return ResourceManager.GetString("SQHeaderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartData can not be null or empty..
        /// </summary>
        internal static string StartDataCannotBeNull {
            get {
                return ResourceManager.GetString("StartDataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Bad source in Traceback..
        /// </summary>
        internal static string TracebackBadSource {
            get {
                return ResourceManager.GetString("TracebackBadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected second sequence name encountered: {0}..
        /// </summary>
        internal static string UnexpectedSecondSequenceName {
            get {
                return ResourceManager.GetString("UnexpectedSecondSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Don&apos;t know element &apos;{1}&apos;..
        /// </summary>
        internal static string UnknownElement {
            get {
                return ResourceManager.GetString("UnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid extensions not set. In case &apos;valid&apos; flag is being used, call ComputeValidExtensions(). Otherwise, use RightExtension / LeftExtension property instead..
        /// </summary>
        internal static string ValidExtensionsNotSet {
            get {
                return ResourceManager.GetString("ValidExtensionsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a comment line with the offset, sequence ID.
        /// </summary>
        internal static string XsvOffsetNotFound {
            get {
                return ResourceManager.GetString("XsvOffsetNotFound", resourceCulture);
            }
        }
    }
}
